{% set version = "125" %}

{% set binaryen_exes = [
    "wasm-as",
    "wasm-ctor-eval",
    "wasm-dis",
    "wasm-emscripten-finalize",
    "wasm-metadce",
    "wasm-opt",
    "wasm-reduce",
    "wasm-shell",
    "wasm2js",
] %}

package:
  name: binaryen
  version: {{ version }}

source:
  url: https://github.com/WebAssembly/binaryen/archive/version_{{ version }}.tar.gz
  sha256: 36177034ef0f0d826fd7dc9ab9d92ef20190a79d69856f764151ffe9c11d7350

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja

test:
  commands:
    {% for exe in binaryen_exes %}
    - which {{ exe }}   # [unix]
    - where {{ exe }}   # [win]
    - {{ exe }} --help  # [build_platform == target_platform]
    {% endfor %}

about:
  home: https://github.com/WebAssembly/binaryen
  license: Apache-2.0
  license_file: LICENSE
  summary: Compiler infrastructure and toolchain library for WebAssembly, in C++

extra:
  recipe-maintainers:
    - jakirkham
    - wolfv
    - martinRenou
